### ISSUE TITLE
chromium-freeworld not loading widevine

### ISSUE THREAD

**Issue by avibrazil** [UnitedRPMs/issues#21] opened 2018-05-31 21:40 UTC
Upgraded to Fedora 28 today and sites like Netflix stopped playing video.
Widevine not listed on chrome://components

$ rpm -qa | grep chromium
chromium-freeworld-libs-66.0.3359.181-2.fc28.x86_64
chromium-freeworld-66.0.3359.181-2.fc28.x86_64
chromium-pepper-flash-29.0.0.171-1.fc28.x86_64
chromium-widevine-1.4.9.1088-1.fc28.x86_64

**Comment by kuboosoft** [comment] 2018-06-03 02:26
@avibrazil We are working about it; Chromium dropped the support widevine by some drastic changes in linux for the moment. Thanks for the report.

**Comment by avibrazil** [comment] 2018-06-03 09:17
Thanks for the reply.

Any old version of chromium I can easily go with dnf on F28 that will make things work again ?

**Comment by avibrazil** [comment] 2018-06-23 08:09
Plain Firefox (with some rpmfusion packages) is fully capable of playing DRM content.
Tested on Netflix and Spotify.

**Comment by kuboosoft** [comment] 2018-06-27 03:06
@avibrazil We need to test widevine; the patches was applied;  can you test if the current chromium-freeworld (67.0.3396.87) version solved the problem? I can't  pay my netflix account in these moment...

**Comment by avibrazil** [comment] 2018-06-27 07:27
That’s too late for me. I’m using Firefox now for my DRM needs. And I was also forced to entirely disable UnitedRPMs because of the Kodi mess. I guess I’m not a user anymore, at lest not for now.

**Comment by kuboosoft** [comment] 2018-06-27 22:22
Well, I can't close yet... We need people testing the update...

**Comment by pasikarkkainen** [comment] 2018-10-08 07:51
Widevine not listed on chrome://components

$ rpm -qa | grep chromium
chromium-freeworld-libs-69.0.3497.100-7.fc28.x86_64
chromium-common-69.0.3497.92-1.fc28.x86_64
chromium-69.0.3497.92-1.fc28.x86_64
chromium-freeworld-69.0.3497.100-7.fc28.x86_64
chromium-libs-media-freeworld-69.0.3497.92-1.fc28.x86_64
chromium-libs-media-69.0.3497.92-1.fc28.x86_64
chromium-widevine-4.10.1192.0-1.fc28.x86_64
chromium-libs-69.0.3497.92-1.fc28.x86_64
chromium-pepper-flash-31.0.0.108-1.fc28.x86_64

**Comment by kuboosoft** [comment] 2018-10-12 09:21
@pasikarkkainen  Make sure Allow sites to play protected content is checked in

`chrome://settings/content/protectedContent`

**Comment by pasikarkkainen** [comment] 2018-10-12 09:45
@kuboosoft yep, "allow sites to play protected content" is enabled / checked in. Still no widevine.. any other ideas?

**Comment by kuboosoft** [comment] 2018-10-12 15:03
@pasikarkkainen Are you using netflix? We need to test if works it here...

Verifying Widevine CDM support
To verify whether widevine works, you can use following ways:

Open [shaka-player-demo.appspot.com ](https://shaka-player-demo.appspot.com/)and load a manifest that uses Widevine.

Open [dash-player.com/demo/drm-test-area](http://www.dash-player.com/demo/drm-test-area/), check whether the page says bitdash uses Widevine in your browser, then play the video.

**Comment by pasikarkkainen** [comment] 2018-10-12 15:11
@kuboosoft  I just tried the urls..

shaka-player-demo.appspot.com doesn't let me choose anything with widevine (they're all inactive / cannot be chosen), and also dash-player.com/demo/drm-test-area says "no DRM".

It feels like I'm missing some configuration setting, but I have no idea which one.

**Comment by kuboosoft** [comment] 2018-10-12 15:47
chromium-69.0.3497.92-1.fc28.x86_64 ??? please remove it... 
I am using widevine without problem...
![GitHub Logo]()
Format: ![Alt Text](https://imgur.com/a/I7Hx7Ub)

**Comment by kuboosoft** [comment] 2018-10-12 16:52
@pasikarkkainen chromium-69.0.3497.92-1.fc28.x86_64 ??? please remove it, chromium in Fedora is different... UnitedRPMs provides chromium-freeworld.

```
[makerpm@localhost ~]$ rpm -q chromium-freeworld
chromium-freeworld-69.0.3497.100-8.fc28.x86_64
```

I am using widevine without problem...
https://imgur.com/a/I7Hx7Ub
https://imgur.com/a/anDEGU8

**Comment by pasikarkkainen** [comment] 2018-10-12 19:11
heh, stupid me. I knew it was going to be something obvious.. yeah, I removed the stock fedora "chromium" rpm, and now using "chromium-freeworld".. and it works using the sites mentioned above!

Thanks a lot.

**Comment by kuboosoft** [comment] 2018-10-13 00:37
@pasikarkkainen No problem. but I can't close it, we need people writing if it works with Netflix...

**Closed as completed** 2019-04-22 07:59 UTC
Labels: bug, enhancement, help wanted

**Comment by Frankstar** [comment] 2019-06-25 23:15
well, im a bit late for that but - it does work fine with netflix.
Fedora 30
``` 
~ rpm -qa | grep chromium
chromium-freeworld-74.0.3729.157-268.1.x86_64
chromium-pepper-flash-32.0.0.207-2.fc30.x86_64
chromium-widevine-4.10.1224.7-1.fc30.x86_64
chromium-freeworld-libs-74.0.3729.157-268.1.x86_64

**Comment by kuboosoft** [comment] 2019-06-27 02:46
```
Hi, please provides
rpm -q ffmpeg
rpm -q fdk-aac-free
```

**Comment by Frankstar** [comment] 2019-06-27 06:13
```
ffmpeg-4.1.3-2.fc30.x86_64
package fdk-aac-free is not installed

**Comment by kuboosoft** [comment] 2019-06-27 06:19
@Frankstar Sorry but you are not using the ffmpeg of UnitedRPMs... The problem isn't here...

```
[makerpm@localhost ~]$ rpm -q unitedrpms
unitedrpms-30-14.fc30.noarch
[makerpm@localhost ~]$ rpm -q ffmpeg
ffmpeg-4.1.3-10.fc30.x86_64
[makerpm@localhost ~]$ rpm -q fdk-aac-free
fdk-aac-free-0.1.6-3.fc30.x86_64
[makerpm@localhost ~]$
```

**Comment by Frankstar** [comment] 2019-06-27 06:23
i think you read my post wrong, i dont have a problem^^ i said everything is working fine.

**Comment by kuboosoft** [comment] 2019-06-27 06:39
@Frankstar You are using the ffmpeg of rpmfusion and this will break the harmony in some programs. For example, our chomium was built with our ffmpeg. I ask you, have you excluded the UnitedRPMs repository in any way? Should we answer for a mix of repositories? Common sense.

https://github.com/UnitedRPMs/WIKI/wiki/Mixes-of-3rd-party-repositories-with-UnitedRPMs
https://github.com/UnitedRPMs/WIKI/wiki

**Comment by Frankstar** [comment] 2019-06-27 06:43
nope, i added the UniteRPMS repo just for chromium-freeworld.
nothing exluded - so far everything works as expected and fine.
But thanks for the tip - will lower uniteRPMs priority.

**Comment by kuboosoft** [comment] 2019-06-27 06:49
@Frankstar I recommend prioritize our updates and avoiding incompatibilities. 
https://github.com/UnitedRPMs/WIKI/wiki/Mixes-of-3rd-party-repositories-with-UnitedRPMs

`"The repositories with the lowest numerical priority number have the highest priority"`

Check the priority in rpmfusion...

UnitedRPMs low priority=high priority
https://github.com/UnitedRPMs/unitedrpms/blob/master/unitedrpms.repo#L6

**Comment by Frankstar** [comment] 2019-06-27 06:54
thanks for the tip!
i think its a bad idea to set the unitedrpms repo to `priority=1` by default - why would u do that?

i set fedora to 10, rpmfusion to 20 and unitedrpms to 90.

**Comment by kuboosoft** [comment] 2019-06-27 06:59
@Frankstar You don't need touch nothing; only check why the ffmpeg of rpmfusion is installed in your system... If other repository has not configured anything, its priority is 99...

`The default priority for repositories is 99`

**Comment by kuboosoft** [comment] 2019-06-27 07:13
@Frankstar 

> "i think its a bad idea to set the unitedrpms repo to priority=1"

No, if you are a demanding user or a user mixing repositories...

**Comment by Frankstar** [comment] 2019-06-27 07:18
ok.
i fixed it for me with
`includepkgs=chromium-freeworld*` in `/etc/yum.repos.d/unitedrpms.repo`

**Comment by kuboosoft** [comment] 2019-06-27 07:24
@Frankstar simple curiosity :smiley: 

`cat /etc/yum.repos.d/unitedrpms.repo`

**Comment by Frankstar** [comment] 2019-06-27 07:28
nothing changed here.
Installed it via 
`dnf install https://github.com/UnitedRPMs/unitedrpms/releases/download/14/unitedrpms-$\(rpm -E %fedora)-14.fc$(rpm -E %fedora).noarch.rpm `

all i added is `includepkgs=chromium-freeworld*`
But here you go:
```
[unitedrpms]
name=unitedrpms $releasever - $basearch
#mirrorlist=https://raw.githubusercontent.com/UnitedRPMs/unitedrpms/master/mirrorlist_x86_64.txt
baseurl=https://sourceforge.net/projects/unitedrpms/files/$releasever/x86_64/
enabled=1
priority=1
includepkgs=chromium-freeworld*
metadata_expire=1d
skip_if_unavailable=1
gpgkey=file:///etc/pki/rpm-gpg/URPMS-GPG-PUBLICKEY-Fedora
gpgcheck=1
repo_gpgcheck=1
type=rpm
enabled_metadata=1

[unitedrpms-source]
name=unitedrpms $releasever - Source
#mirrorlist=https://raw.githubusercontent.com/UnitedRPMs/unitedrpms/master/mirrorlist_source.txt
baseurl=https://sourceforge.net/projects/unitedrpms/files/$releasever/srpm/
enabled=0
priority=1
metadata_expire=1d
skip_if_unavailable=1
gpgkey=file:///etc/pki/rpm-gpg/URPMS-GPG-PUBLICKEY-Fedora
gpgcheck=1
repo_gpgcheck=1
type=rpm

[unitedrpms-debuginfo]
name=unitedrpms $releasever - $basearch - Debug
#mirrorlist=https://raw.githubusercontent.com/UnitedRPMs/unitedrpms/master/mirrorlist_debug.txt
baseurl=https://sourceforge.net/projects/unitedrpms/files/$releasever/x86_64/debug/
enabled=0
priority=1
metadata_expire=1d
skip_if_unavailable=1
gpgkey=file:///etc/pki/rpm-gpg/URPMS-GPG-PUBLICKEY-Fedora
gpgcheck=1
repo_gpgcheck=1
type=rpm

**Comment by kuboosoft** [comment] 2019-06-27 07:37
@Frankstar Very strange; the priority is "1" If you are using unitedrpms it should avoid a package with lower release... ¿bug? maybe. I need test it and open a bugzilla report... Check the priority in my pc...

```
[root@localhost makerpm]# dnf clean all && dnf -y update
44 files removed
unitedrpms 30 - x86_64                          105 kB/s | 1.1 MB     00:10    
Fedora Modular 30 - x86_64                      366 kB/s | 2.7 MB     00:07    
Fedora Modular 30 - x86_64 - Updates            376 kB/s | 2.2 MB     00:05    
Fedora 30 - x86_64 - Updates                    432 kB/s |  15 MB     00:35    
Fedora 30 - x86_64                              466 kB/s |  70 MB     02:33    
google-chrome-unstable                           10 kB/s | 3.4 kB     00:00    
Last metadata expiration check: 0:00:01 ago on Thu Jun 27 01:36:06 2019.
Dependencies resolved.
================================================================================
 Package                      Arch       Version              Repository   Size
================================================================================
Upgrading:
 blivet-data                  noarch     1:3.1.4-1.fc30       updates     102 k
 glusterfs                    x86_64     6.3-1.fc30           updates     608 k
 glusterfs-api                x86_64     6.3-1.fc30           updates      87 k
 glusterfs-cli                x86_64     6.3-1.fc30           updates     190 k
 glusterfs-client-xlators     x86_64     6.3-1.fc30           updates     812 k
 glusterfs-fuse               x86_64     6.3-1.fc30           updates     134 k
 glusterfs-libs               x86_64     6.3-1.fc30           updates     395 k
 libnfsidmap                  x86_64     1:2.4.1-0.fc30       updates      63 k
 mutter                       x86_64     3.32.2-2.fc30        updates     2.4 M
 nfs-utils                    x86_64     1:2.4.1-0.fc30       updates     404 k
 python3-blivet               noarch     1:3.1.4-1.fc30       updates     870 k

Transaction Summary
================================================================================
Upgrade  11 Packages

Total download size: 6.0 M
Downloading Packages:
(1/11): glusterfs-api-6.2-1.fc30_6.3-1.fc30.x86  27 kB/s |  13 kB     00:00    
(2/11): glusterfs-6.2-1.fc30_6.3-1.fc30.x86_64.  74 kB/s |  39 kB     00:00    
(3/11): glusterfs-client-xlators-6.2-1.fc30_6.3  30 kB/s |  17 kB     00:00    
(4/11): glusterfs-libs-6.2-1.fc30_6.3-1.fc30.x8  60 kB/s |  14 kB     00:00    
(5/11): glusterfs-fuse-6.2-1.fc30_6.3-1.fc30.x8 242 kB/s |  69 kB     00:00    
(6/11): libnfsidmap-2.3.4-2.fc30_2.4.1-0.fc30.x  90 kB/s |  23 kB     00:00    
(7/11): mutter-3.32.2-1.fc30_3.32.2-2.fc30.x86_ 280 kB/s | 113 kB     00:00    
[DRPM 1/7] glusterfs-api-6.2-1.fc30_6.3-1.fc30.x86_64.drpm: done               
(8/11): blivet-data-3.1.4-1.fc30.noarch.rpm     140 kB/s | 102 kB     00:00    
(9/11): glusterfs-cli-6.3-1.fc30.x86_64.rpm     188 kB/s | 190 kB     00:01    
(10/11): nfs-utils-2.4.1-0.fc30.x86_64.rpm      202 kB/s | 404 kB     00:02    
(11/11): python3-blivet-3.1.4-1.fc30.noarch.rpm 305 kB/s | 870 kB     00:02    
[DRPM 2/7] glusterfs-6.2-1.fc30_6.3-1.fc30.x86_64.drpm: done                   
[DRPM 3/7] glusterfs-client-xlators-6.2-1.fc30_6.3-1.fc30.x86_64.drpm: done    
[DRPM 4/7] glusterfs-libs-6.2-1.fc30_6.3-1.fc30.x86_64.drpm: done              
[DRPM 5/7] glusterfs-fuse-6.2-1.fc30_6.3-1.fc30.x86_64.drpm: done              
[DRPM 6/7] libnfsidmap-2.3.4-2.fc30_2.4.1-0.fc30.x86_64.drpm: done             
[DRPM 7/7] mutter-3.32.2-1.fc30_3.32.2-2.fc30.x86_64.drpm: done                
--------------------------------------------------------------------------------
Total                                           122 kB/s | 1.8 MB     00:15     
Delta RPMs reduced 6.0 MB of updates to 1.8 MB (69.1% saved)
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Running scriptlet: glusterfs-libs-6.3-1.fc30.x86_64                       1/1 
  Upgrading        : glusterfs-libs-6.3-1.fc30.x86_64                      1/22 
  Running scriptlet: glusterfs-6.3-1.fc30.x86_64                           2/22 
  Upgrading        : glusterfs-6.3-1.fc30.x86_64                           2/22 
  Running scriptlet: glusterfs-6.3-1.fc30.x86_64                           2/22 
  Upgrading        : glusterfs-client-xlators-6.3-1.fc30.x86_64            3/22 
  Upgrading        : libnfsidmap-1:2.4.1-0.fc30.x86_64                     4/22 
  Upgrading        : blivet-data-1:3.1.4-1.fc30.noarch                     5/22 
  Upgrading        : python3-blivet-1:3.1.4-1.fc30.noarch                  6/22 
  Running scriptlet: nfs-utils-1:2.4.1-0.fc30.x86_64                       7/22 
  Upgrading        : nfs-utils-1:2.4.1-0.fc30.x86_64                       7/22 
  Running scriptlet: nfs-utils-1:2.4.1-0.fc30.x86_64                       7/22 
  Upgrading        : glusterfs-api-6.3-1.fc30.x86_64                       8/22 
  Upgrading        : glusterfs-fuse-6.3-1.fc30.x86_64                      9/22 
  Upgrading        : glusterfs-cli-6.3-1.fc30.x86_64                      10/22 
  Upgrading        : mutter-3.32.2-2.fc30.x86_64                          11/22 
  Cleanup          : glusterfs-fuse-6.2-1.fc30.x86_64                     12/22 
  Cleanup          : glusterfs-api-6.2-1.fc30.x86_64                      13/22 
  Cleanup          : glusterfs-6.2-1.fc30.x86_64                          14/22 
  Running scriptlet: glusterfs-6.2-1.fc30.x86_64                          14/22 
  Cleanup          : glusterfs-cli-6.2-1.fc30.x86_64                      15/22 
  Cleanup          : glusterfs-client-xlators-6.2-1.fc30.x86_64           16/22 
  Running scriptlet: nfs-utils-1:2.3.4-2.fc30.x86_64                      17/22 
  Cleanup          : nfs-utils-1:2.3.4-2.fc30.x86_64                      17/22 
  Running scriptlet: nfs-utils-1:2.3.4-2.fc30.x86_64                      17/22 
  Cleanup          : python3-blivet-1:3.1.3-3.fc30.noarch                 18/22 
  Cleanup          : blivet-data-1:3.1.3-3.fc30.noarch                    19/22 
  Cleanup          : libnfsidmap-1:2.3.4-2.fc30.x86_64                    20/22 
  Cleanup          : glusterfs-libs-6.2-1.fc30.x86_64                     21/22 
  Cleanup          : mutter-3.32.2-1.fc30.x86_64                          22/22 
  Running scriptlet: mutter-3.32.2-1.fc30.x86_64                          22/22 
/sbin/ldconfig: /lib64/libWidgets.so.1 is not a symbolic link


/sbin/ldconfig: /lib64/libWidgets.so.1 is not a symbolic link


  Verifying        : blivet-data-1:3.1.4-1.fc30.noarch                     1/22 
  Verifying        : blivet-data-1:3.1.3-3.fc30.noarch                     2/22 
  Verifying        : glusterfs-6.3-1.fc30.x86_64                           3/22 
  Verifying        : glusterfs-6.2-1.fc30.x86_64                           4/22 
  Verifying        : glusterfs-api-6.3-1.fc30.x86_64                       5/22 
  Verifying        : glusterfs-api-6.2-1.fc30.x86_64                       6/22 
  Verifying        : glusterfs-cli-6.3-1.fc30.x86_64                       7/22 
  Verifying        : glusterfs-cli-6.2-1.fc30.x86_64                       8/22 
  Verifying        : glusterfs-client-xlators-6.3-1.fc30.x86_64            9/22 
  Verifying        : glusterfs-client-xlators-6.2-1.fc30.x86_64           10/22 
  Verifying        : glusterfs-fuse-6.3-1.fc30.x86_64                     11/22 
  Verifying        : glusterfs-fuse-6.2-1.fc30.x86_64                     12/22 
  Verifying        : glusterfs-libs-6.3-1.fc30.x86_64                     13/22 
  Verifying        : glusterfs-libs-6.2-1.fc30.x86_64                     14/22 
  Verifying        : libnfsidmap-1:2.4.1-0.fc30.x86_64                    15/22 
  Verifying        : libnfsidmap-1:2.3.4-2.fc30.x86_64                    16/22 
  Verifying        : mutter-3.32.2-2.fc30.x86_64                          17/22 
  Verifying        : mutter-3.32.2-1.fc30.x86_64                          18/22 
  Verifying        : nfs-utils-1:2.4.1-0.fc30.x86_64                      19/22 
  Verifying        : nfs-utils-1:2.3.4-2.fc30.x86_64                      20/22 
  Verifying        : python3-blivet-1:3.1.4-1.fc30.noarch                 21/22 
  Verifying        : python3-blivet-1:3.1.3-3.fc30.noarch                 22/22 

Upgraded:
  blivet-data-1:3.1.4-1.fc30.noarch           glusterfs-6.3-1.fc30.x86_64       
  glusterfs-api-6.3-1.fc30.x86_64             glusterfs-cli-6.3-1.fc30.x86_64   
  glusterfs-client-xlators-6.3-1.fc30.x86_64  glusterfs-fuse-6.3-1.fc30.x86_64  
  glusterfs-libs-6.3-1.fc30.x86_64            libnfsidmap-1:2.4.1-0.fc30.x86_64 
  mutter-3.32.2-2.fc30.x86_64                 nfs-utils-1:2.4.1-0.fc30.x86_64   
  python3-blivet-1:3.1.4-1.fc30.noarch       

Complete!
[root@localhost makerpm]# 
```
